set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN H15 [get_ports DOUT]
set_property PACKAGE_PIN V13 [get_ports PD_SCK]
set_property PACKAGE_PIN V12 [get_ports pwm1]
set_property PACKAGE_PIN K18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports DOUT]
set_property IOSTANDARD LVCMOS33 [get_ports PD_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports pwm1]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk]